package uk.ac.tees.mad.payclock.data.models

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a job with its specific details, updated for synchronization.
 * This class is now a Room Entity, representing the 'jobs' table in the database.
 *
 * @property id The unique identifier for the job. Auto-generated by Room.
 * @property name The name or title of the job.
 * @property hourlyRate The rate of pay per hour for this job.
 * @property breakTimeInMinutes The standard unpaid break time for a shift, in minutes.
 * @property lastModifiedTimestamp The timestamp of the last local update (used for conflict resolution).
 * @property isPendingSync Flag indicating if this job needs to be pushed to the server.
 */
@Entity(tableName = "jobs")
data class Job(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    val name: String,
    val hourlyRate: Double,
    val breakTimeInMinutes: Int,
    val lastModifiedTimestamp: Long = System.currentTimeMillis(),
    val isPendingSync: Boolean = false
)
