package uk.ac.tees.mad.payclock.features.timelog.data

import androidx.room.Entity
import androidx.room.PrimaryKey
import com.google.firebase.firestore.DocumentId
import com.google.firebase.firestore.ServerTimestamp
import java.util.Date

/**
 * Represents a time log for a specific job, tracking work shifts.
 * This class is used as a Room entity to store time log data locally and is also
 * synchronized with Firestore.
 *
 * @property id Unique identifier for the time log, generated by Firestore.
 * @property userId The ID of the user this time log belongs to.
 * @property jobId The ID of the job associated with this time log.
 * @property startTime The timestamp when the work shift started. Marked with @ServerTimestamp to be set by Firestore.
 * @property endTime The timestamp when the work shift ended. Null if the shift is ongoing.
 * @property duration The total duration of the work shift in minutes. Null if the shift is ongoing.
 * @property startLatitude The latitude where the shift started. Null if location was not recorded.
 * @property startLongitude The longitude where the shift started. Null if location was not recorded.
 * @property endLatitude The latitude where the shift ended. Null if location was not recorded.
 * @property endLongitude The longitude where the shift ended. Null if location was not recorded.
 * @property startAddress The address (reverse-geocoded) where the shift started. Null if not available.
 * @property endAddress The address (reverse-geocoded) where the shift ended. Null if not available.
 * @property lastUpdated The timestamp of the last modification to this time log entry.
 */
@Entity(tableName = "time_logs")
data class TimeLog(
    @PrimaryKey
    @DocumentId
    val id: String = "",
    val userId: String = "",
    val jobId: String = "",
    @ServerTimestamp
    val startTime: Date? = null,
    var endTime: Date? = null,
    var duration: Long? = null, // Duration in minutes

    // Added nullable location fields for start and end
    val startLatitude: Double? = null,
    val startLongitude: Double? = null,
    var endLatitude: Double? = null,
    var endLongitude: Double? = null,

    // Added nullable address fields (reverse-geocoded)
    val startAddress: String? = null,
    var endAddress: String? = null,

    var lastUpdated: Date? = null
)